name: Publish Package

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  release:
    runs-on: ubuntu-latest
    outputs:
     version_changed: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v3

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true

      - uses: rickstaa/action-create-tag@v1
        if: steps.check.outputs.changed == 'true'
        with:
          tag: "v${{ steps.check.outputs.version }}"

      - name: Create Release
        if: steps.check.outputs.changed == 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.check.outputs.version }}"
          generateReleaseNotes: true
          draft: false

  package:
    name: "Create npm package"
    needs: [release]
    if: (needs.release.outputs.version_changed == 'true') && (github.repository_owner == 'badlabs')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: npm pack
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: "*.tgz"

  publish-gh:
    name: Publish to GitHub Packages
    needs: [package]
    runs-on: ubuntu-latest
    if: github.repository_owner == 'badlabs'
    steps:
      - name: Upload
        uses: actions/download-artifact@v2
        with:
          name: package
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@badlabs"
      - run: echo "registry=https://npm.pkg.github.com/@badlabs" >> .npmrc
      - run: npm publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_PACKAGES_TOKEN}}

  publish-npm:
    name: Publish to NPM
    needs: [package]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}